export const alertatypes = {
    MOSTRAR_ALERTA:'MOSTRAR_ALERTA',
    CERRAR_ALERTA : 'CERRAR_ALERTA',
}

export const emailTypes = {
    SEND_CONTACT_EMAIL : 'SEND_CONTACT_EMAIL', 
    SEND_CONTACT_EMAIL_STATUS : 'SEND_CONTACT_EMAIL_STATUS', 
}

export const menuTypes = {
    OPEN_MENU : 'OPEN_MENU', 
    CLOSE_MENU : 'CLOSE_MENU', 
}

export const fullImageTypes = {
    OPEN_IMAGE : 'OPEN_IMAGE',
    CLOSE_IMAGE : 'CLOSE_IMAGE',
    SET_SELECTED_IMAGE : 'SET_SELECTED_IMAGE', 
}

export const socialEventTypes = {
    GET_ALL_SOCIALEVENTS : 'GET_ALL_SOCIALEVENTS',
    GET_ALL_SOCIALEVENTS_STATUS : 'GET_ALL_SOCIALEVENTS_STATUS',
    GET_HOME_SOCIALEVENTS : 'GET_HOME_SOCIALEVENTS',
    GET_HOME_SOCIALEVENTS_STATUS : 'GET_HOME_SOCIALEVENTS_STATUS',
    GET_SOCIALEVENT_BY_ID : 'GET_SOCIALEVENT_BY_ID',
    GET_SOCIALEVENT_BY_ID_STATUS : 'GET_SOCIALEVENT_BY_ID_STATUS',
}

export const authTypes = {
    CREATE_ACCOUNT : 'CREATE_ACCOUNT',
    CREATE_ACCOUNT_STATUS : 'CREATE_ACCOUNT_STATUS',
    CONFIRM_ACCOUNT : 'CONFIRM_ACCOUNT',
    CONFIRM_ACCOUNT_STATUS : 'CONFIRM_ACCOUNT_STATUS',
    GET_AUTH_USER : 'GET_AUTH_USER',
    GET_AUTH_USER_STATUS : 'GET_AUTH_USER_STATUS',
    LOGIN : 'LOGIN',
    LOGIN_STATUS : 'LOGIN_STATUS',
    LOGOUT : 'LOGOUT',
    RESEND_CODE : 'RESEND_CODE',
    RESEND_CODE_STATUS : 'RESEND_CODE_STATUS'
}

export const imageTypes = {
    CREATE_IMAGE : 'CREATE_IMAGE',
    CREATE_IMAGE_STATUS : 'CREATE_IMAGE_STATUS',
    GET_ALL_IMAGES : 'GET_ALL_IMAGES',
    GET_ALL_IMAGES_STATUS : 'GET_ALL_IMAGES_STATUS',
    DELETE_IMAGE_BY_ID : 'DELETE_IMAGE_BY_ID',
    DELETE_IMAGE_BY_ID_STATUS : 'DELETE_IMAGE_BY_ID_STATUS',
}